/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2095.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_display_service.h" 
#include "preprocessor.h"
#include "storage.h"

static ble_display_service_t    m_display_service; 

/**@brief Function for handling the Display Service events.
 *
 * @details This function will be called for all Display Service events which are passed to
 *          the application.
 *
 * @param[in]   p_display_service   Display Service structure.
 * @param[in]   p_evt   Event received from the Display Service.
 */
static void on_display_service_evt(ble_display_service_t * p_display_service, ble_display_service_evt_t * p_evt)
{
	switch (p_evt->evt_type)
	{ 
	case BLE_DISPLAY_SERVICE_RECORD_NUMBER_EVT_WRITE:
		app_trace_log("[Bluetooth_IF]: DISPLAY_SERVICE_RECORD_NUMBER evt WRITE. \r\n");
		
	// The caller is requesting a reset record
		
		if (p_evt->params.record_number.record_number == 0xFF)
		{
			// If they put in 0xFF, they want the current value
			ble_display_service_record_t send_record;
			
			send_record.record_number = get_next_record();
			send_record.seconds_running = seconds_with_water;
			send_record.timestamp = seconds;
			
			ble_display_service_record_set(&m_display_service,
				&send_record);
			ble_display_service_record_send(&m_display_service,
				&send_record);
			
			// Save this record
			if (!save_record(&send_record))
			{
				// We encountered an error if we're here
				//  We should probably find a way to handle it
			}
			
			seconds_with_water = 0;
		}
		else
		{
			// Go back in history and recover a record
			
			ble_display_service_record_t record;
			record.record_number = p_evt->params.record_number.record_number;
			
			if (get_record(&record))
			{
				ble_display_service_record_send(&m_display_service, &record);
			}
		}
		
		
		break; 
	case BLE_DISPLAY_SERVICE_RECORD_EVT_NOTIFICATION_ENABLED:
		app_trace_log("[Bluetooth_IF]: DISPLAY_SERVICE_RECORD evt NOTIFICATION_ENABLED. \r\n");
		break;
	case BLE_DISPLAY_SERVICE_RECORD_EVT_NOTIFICATION_DISABLED:
		app_trace_log("[Bluetooth_IF]: DISPLAY_SERVICE_RECORD evt NOTIFICATION_DISABLED. \r\n");
		break;
	case BLE_DISPLAY_SERVICE_RECORD_EVT_CCCD_WRITE:
		app_trace_log("[Bluetooth_IF]: DISPLAY_SERVICE_RECORD evt CCCD_WRITE. \r\n");
		break; 
	default:
	    // No implementation needed.
		break;
	}
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
	uint32_t    err_code; 
	ble_display_service_init_t    display_service_init; 
    

	    // Initialize Display Service.
	memset(&display_service_init, 0, sizeof(display_service_init));

	display_service_init.evt_handler = on_display_service_evt; 
	memset(&display_service_init.ble_display_service_record_number_initial_value.record_number,
		0x00,
		sizeof(display_service_init.ble_display_service_record_number_initial_value.record_number));
	memset(&display_service_init.ble_display_service_record_initial_value.record_number,
		0x00,
		sizeof(display_service_init.ble_display_service_record_initial_value.record_number));
	memset(&display_service_init.ble_display_service_record_initial_value.seconds_running,
		0x00,
		sizeof(display_service_init.ble_display_service_record_initial_value.seconds_running));
	memset(&display_service_init.ble_display_service_record_initial_value.timestamp,
		0x00,
		sizeof(display_service_init.ble_display_service_record_initial_value.timestamp));

	err_code = ble_display_service_init(&m_display_service, &display_service_init);
	if (err_code != NRF_SUCCESS)
	{
		return err_code;
	} 

	return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
	ble_display_service_on_ble_evt(&m_display_service, p_ble_evt); 
}
